### ISSUE TITLE
Mapeo de Entidades Usuario correspondiente a pagina registrarme.html

### ISSUE THREAD

**Issue by Alexis-Correjidor** [Alexis-Correjidor/TPfinal#33]
Atributos correspondiente a Usuario:

-Nombre
- Apellido
- E-mail
- Fecha nacimiento
- Teléfono
- Sexo
- Estatura.

**Comment by gonzanv** [comment]
Mapeo de la entidad Usuario hecho junto con las validaciones.

[branch](https://github.com/Alexis-Correjidor/TPfinal/tree/Mapeo_Entidad_Usuario_VelazquezGonzalo)
