### ISSUE TITLE
 Integración capa Service de pagina registrarme.html

### ISSUE THREAD

**Issue by Alexis-Correjidor** [Alexis-Correjidor/TPfinal#37]
Crear paquete ar.edu.unju.fi.service
Implementar la interface de servicio
Determinar de forma clara las tareas 
e Implementación de Servicio en paquete ar.edu.unju.fi.service.imp

**Comment by gonzanv** [comment]
[branch](https://github.com/Alexis-Correjidor/TPfinal/tree/CapaServiceyRepositoryparaUsuario_VelazquezGonzalo)
