### ISSUE TITLE
Integracion capa Repository para registrarme.html

### ISSUE THREAD

**Issue by Alexis-Correjidor** [Alexis-Correjidor/TPfinal#42]
Integrar una capa Repository en el proyecto
Realizar conexión a Base de Dato con Mysql
Implementar Interface de Servicio

**Comment by gonzanv** [comment]
[branch](https://github.com/Alexis-Correjidor/TPfinal/tree/CapaServiceyRepositoryparaUsuario_VelazquezGonzalo)
